### ISSUE TITLE
How to get 'pubchem_roberta_10M_large.pt'?

### ISSUE THREAD

**Issue by LinnaWang-Lena** [ssshddd/DrugRec#5]
Hello, Thank you for publishing this great work!  I have a question about the Step 3:  running input_smiles_iii.py. Did you employ the pretrained model of [DVMP](https://github.com/microsoft/DVMP) for SMILES tokenization?  May I ask if you trained the model by yourself or got the pretrained model from their author?  Thank you.

**Comment by ssshddd** [comment]
We get the parameters of DVMP (https://github.com/microsoft/DVMP) from their authors and offline obtain the SMILES representations for each medication.

**Comment by LuBiXian** [comment]
尊敬的作者，我查看了 https://github.com/microsoft/DVMP 的目录，发现 DVMP 的作者没有上传 'pubchem_roberta_10M_large.pt' 的预训练检查点，您能直接分享模型吗？

**Comment by fxx765** [comment]
请问在哪里可以获得pubchem_roberta_10M_large.pt
